{{- range $namespace := .Values.namespaces }}
---
{{- if ne $namespace "monitoring" -}}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ $namespace }}
  namespace: {{ $namespace }}
  labels:
    alertmanagerConfig: {{ $namespace }}
spec:
  route:
    receiver: 'telegram'
    matchers:
    - name: severity
      regex: true
      value: "warning|critical"
  receivers:
  - name: 'telegram'
    telegramConfigs:
    - apiURL: https://api.telegram.org
      botToken:
        key: token
        name: alertmanager-telegram-token
        optional: false
      chatID: -1002117545398
      sendResolved: true
      parseMode: HTML
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-telegram-token
  namespace: {{ $namespace }}
spec:
  data:
  - remoteRef:
      key: TELEGRAM_PROMETHEUS_TOKEN
    secretKey: token
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: mgmt-prod
{{- end }}
{{- end }}
