apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterissuer.clusterrole.name }}
rules:
- apiGroups: ["", "cert-manager.io"]
  resources: ["secrets", "clusterissuers"]
  verbs: ["*"]
