{{- range $serviceaccount := .Values.github.serviceaccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceaccount.name }}
  namespace: {{ $serviceaccount.namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $serviceaccount.name }}-token"
  namespace: {{ $serviceaccount.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ $serviceaccount.name }}
type: kubernetes.io/service-account-token
{{- end }}
