apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.github.clusterrole.name }}
rules:
- apiGroups: ["", "apps", "batch", "networking.k8s.io", "acid.zalan.do"]
  resources: ["deployments", "configmaps", "secrets", "persistentvolumes", "persistentvolumeclaims", "pods", "services", "ingresses", "statefulsets", "replicasets", "cronjobs", "jobs", "postgresqls"]
  verbs: ["list", "get", "update", "create", "watch", "edit", "patch", "delete"]
