{{- range $serviceaccount := .Values.github.serviceaccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceaccount.name }}
  namespace: {{ $serviceaccount.namespace }}
{{- end }}
