apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.polarlightstate.rolebinding.name }}
  namespace: {{ .Values.polarlightstate.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.polarlightstate.role.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.polarlightstate.serviceaccount.name }}
  namespace: {{ .Values.polarlightstate.namespace }}
