apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.postgresoperator.role.name }}
  namespace: {{ .Values.postgresoperator.namespace }}
rules:
- apiGroups:
  - apps
  - batch
  - networking.k8s.io
  - acid.zalan.do
  resources:
  - deployments
  - configmaps
  - secrets
  - persistentvolumes
  - persistentvolumeclaims
  - pods
  - services
  - ingresses
  - statefulsets
  - replicasets
  - cronjobs
  - jobs
  - postgresqls
  verbs:
  - list
  - get
  - update
  - create
  - watch
  - edit
  - patch
  - delete
