name: Build and deploy

on:
  push:
  pull_request:

jobs:
  lint:
    name: "helm lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: update tag in manifest.yml
        run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - name: install helm chart
        uses: BlindfoldedSurgery/github-action-helm@v0.3.0
        with:
          raw_command: lint --strict
